# Source of the FHIR public test servers

# https://confluence.hl7.org/display/FHIR/Public+Test+Servers

# Connectathon test servers

# https://confluence.hl7.org/display/FHIR/Test+Servers

# FHIR R4

http://hapi.fhir.org/baseR4

# AEGIS.net, Inc.:

# R4 - http://wildfhir4.aegis.net/fhir4-0-1

# AETNA

# https://developerportal.aetna.com/gettingstarted

# eHealth Exchange

# R4 - http://52.10.37.229:52774/hubonfhir/r4

# Telstra Health(HealthConnex):

# R4 server: http://sqlonfhir-r4.azurewebsites.net/fhir

# R4 vhdir demo server: https://vhdir-demo.fhir.org/fhir

# Terminz (NZ Terminology Service R4): https://terminz.azurewebsites.net/fhir

# Helios Software: http://r4.heliossoftware.com/fhir

# CorroHealth (T-System):

# R4 Open: https://fhirsandbox1.tsysinteropsvcs.net:8100/r4/sites/123

# For test patient with data, use Patient ID=1.

# R4 Secure: https://fhirsandbox2.tsysinteropsvcs.net:8100/r4/sites/123

# Grahame's test server, pascal-based FHIR server

# @baseurl = http://test.fhir.org/r4

# AEGIS WildFHIR

# R4 Official v4.0.1 -

# @baseurl = http://wildfhir4.aegis.net/fhir4-0-1

# Test client interface:

# http://wildfhir4.aegis.net/fhir4-0-1-gui

# HAPI FHIR Reference Server, java-based FHIR server,

# University Health Network, the hapi developer / James Agnew

# R4 Endpoint:

# @baseurl = http://hapi.fhir.org/baseR4

# R5 Endpoint:

# @baseurl = http://hapi.fhir.org/baseR5

# Open-source app launcher + based on HAPI FHIR server

# @baseurl = https://launch.smarthealthit.org/

# Health Samurai's HAPI FHIR server with postgresql database

# https://health-samurai.io/aidbox

# NLM's HAPI FHIR servers (reset weekly):

# @baseurl = https://lforms-fhir.nlm.nih.gov/baseR4

# Vonk - .NET based FHIR Server by Firely -

# R4 Endpoint:

# @baseurl = http://vonk.fire

# R5 endpoint:

# @baseurl = https://labs.vonk.fire.ly

# === EMR providers ===

# Cerner's Sandbox Endpoints for R4:

# Open -

# @baseurl = https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d

# With OAuth 2 Provider access -

# @baseurl = https://fhir-ehr-code.cerner.com/dstu2/ec2458f2-1e24-41c8-b71b-0e701af7583d

# With OAuth 2 Patient access -

# @baseurl = https://fhir-myrecord.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d

# From sandy

# Cerner: Auth details on http://fhir.cerner.com/authorization/#registration

# R4 patient access: https://fhir-myrecord.stagingcerner.com/beta/ec2458f2-1e24-41c8-b71b-0e701af7583d/

# R4 provider and system access: https://fhir-ehr.stagingcerner.com/beta/ec2458f2-1e24-41c8-b71b-0e701af7583d/

# R4 insecure access: https://fhir-open.stagingcerner.com/beta/ec2458f2-1e24-41c8-b71b-0e701af7583d/

# R5 insecure (mostly subscriptions): https://fhir-open.stagingcerner.com/beta/r5/ec2458f2-1e24-41c8-b71b-0e701af7583d/

# Epic's Sandbox

# @baseurl = http://open.epic.com/Interface/FHIR

# Allscripts STU3 Sandbox (OAuth)

# @baseurl = http://twdev.open.allscripts.com/FHIR

# Allscripts R4 Secure:

# baseurl = https://fhirdev.open.allscripts.com/fhir-r4

# EMR Direct R4 Secure:

# baseurl = https://stage.healthtogo.me:8181/fhir/r4/stage

# === healthcare providers ===

# Michigan Health Information Network (open)

# @baseurl = http://52.72.172.54:8080/fhir/home

=== Payers ======

# MITRE

# Formulary (Open): https://davinci-drug-formulary-ri.logicahealth.org/fhir

# Plan-Net (Open): https://davinci-plan-net-ri.logicahealth.org/fhir

# CRD: https://davinci-crd.logicahealth.org/r4

# DTR: https://davinci-dtr.logicahealth.org/

# PAS (Backend Authenticated): https://davinci-prior-auth.logicahealth.org/fhir

# See https://github.com/HL7-DaVinci/prior-auth/wiki/Connectathon-README for authentication details

# Carin-BB (Authenticated): http://cpcds-ri.org/cpcds-server/fhir/

# See https://github.com/carin-alliance/cpcds-server-ri/wiki/Connectathon-README for authentication details

# Patient Access API (open): https://api.logicahealth.org/DVJan21CnthnPDex/open

# Patient Access API (Authenticated): https://api.logicahealth.org/DVJan21CnthnPDex/data

# US Core (Authenticated, login instructions): http://inferno.healthit.gov/reference-server/r4

# Optum:

# Plan-Net/Provider Directory

# Authenticated server:

# R4: https://fhir.stg.flex-nonprod.optum.com/R4/

# metadata (CapabilityStatement): https://fhir.stg.flex-nonprod.optum.com/R4/metadata

# Requires registration through the UHC portal: https://portal.stg.flex-nonprod.optum.com/homepage

# Non-authenticated server:

# R4: https://appnameformularlyconnectathonjan2021.azurewebsites.net/R4/

# metadata (CapabilityStatement): https://appnameformularlyconnectathonjan2021.azurewebsites.net/R4/metadata

=== Consulting, individual, app developer ====

# CareEvolution HIEBus Info and access request

# https://fhir.careevolution.com/Master.Adapter1.WebClient/fhir

# Protected (SMART-on-FHIR) R4 end-point:

# @baseurl = https://fhir.careevolution.com/Master.Adapter1.WebClient/api/fhir-r4

# Alphora

# R4 CDS (Open): https://cds-sandbox.alphora.com/cqf-ruler-r4/fhir

# R4 CQM (Open): https://cqm-sandbox.alphora.com/cqf-ruler-r4/fhir

# InteropX:

# R4: https://demo.interopx.com.com/InteropXFHIR/fhir/

# metadata (CapabilityStatement): https://demo.interopx.com.com/InteropXFHIR/fhir/metadata

# Requires registration through Client portal: https://demo.interopx.com/ix-auth-server/

# PDEX Plan-Net (Open Server): https://demo.interopx.com/fhir-pdex-plannet/fhir/

# Onyx SAFHIR

# https://nw-sf-con-uses0-dmdh-safhirapim.azure-api.net/api/ (You can see all the IGs from R4, PDEX, Plannet, Formulary, Carin-BB, and US-Core) here

# Developer Registration https://con.safhir.io

# User: Test25001@dmd.com Pwd: Track@03

# Helios FHIR Server

# http://r4.heliossoftware.com/fhir - open sandbox
# Supports R4 read and write for all FHIR Resource types

